const thaiAlphabet = {
    consonants: [
        { character: 'ก', name: 'กอ ไก่', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20chicken%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ข', name: 'ขอ ไข่', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20egg%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ฃ', name: 'ฃอ ขวด', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20bottle%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ค', name: 'คอ ควาย', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20buffalo%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ฅ', name: 'ฅอ คอน', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20squirrel%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ฆ', name: 'ฆอ ระฆัง', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20bell%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ง', name: 'งอ งู', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20snake%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'จ', name: 'จอ จาน', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20plate%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ฉ', name: 'ฉอ ฉิ่ง', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20cymbal%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ช', name: 'ชอ ช้าง', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20elephant%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ซ', name: 'ซอ โซ้', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20altar%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ฌ', name: 'ฌอ เฌอ', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20deer%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ญ', name: 'ญอ หญิง', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20woman%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ฎ', name: 'ฎอ ชฎา', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20headdress%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ฏ', name: 'ฏอ ปฏัก', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20spear%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ฐ', name: 'ฐอ ฐาน', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20pedestal%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ฑ', name: 'ฑอ มะนดา', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20moon%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ฒ', name: 'ฒอ ผู้เฒ่า', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20old%20man%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ณ', name: 'ณอ เณร', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20monk%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ด', name: 'ดอ เด็ก', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20child%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ต', name: 'ตอ เต่า', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20turtle%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ถ', name: 'ถอ ถุง', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20bag%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ท', name: 'ทอ ทหาร', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20soldier%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ธ', name: 'ธอ ธง', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20flag%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'น', name: 'นอ หนู', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20mouse%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'บ', name: 'บอ ใบไม้', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20leaf%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ป', name: 'ปอ ปลา', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20fish%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ผ', name: 'ผอ ผึ้ง', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20bee%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ฝ', name: 'ฝอ ฝา', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20lid%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'พ', name: 'พอ พาน', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20tray%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ฟ', name: 'ฟอ ฟัน', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20tooth%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ภ', name: 'ภอ สำเภา', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20ship%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ม', name: 'มอ ม้า', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20horse%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ย', name: 'ยอ ยักษ์', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20giant%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ร', name: 'รอ เรือ', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20boat%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ล', name: 'ลอ ลิง', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20monkey%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ว', name: 'วอ แหวน', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20ring%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ศ', name: 'ศอ ศาลา', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20pavilion%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ษ', name: 'ษอ ฤๅษี', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20hermit%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ส', name: 'สอ เสือ', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20tiger%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ห', name: 'หอ หีบ', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20box%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ฬ', name: 'ฬอ จุฬา', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20kite%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'อ', name: 'ออ อ่าง', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20basin%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ฮ', name: 'ฮอ นกฮูก', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20owl%20for%20kids%20thai%20style&image_size=square_hd' }
    ],
    
    vowels: [
        { character: 'อะ', name: 'สระอะ', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20apple%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'อา', name: 'สระอา', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20mango%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'อิ', name: 'สระอิ', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20insect%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'อี', name: 'สระอี', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20tree%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'อึ', name: 'สระอึ', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20mushroom%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'อื', name: 'สระอื', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20moon%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'อุ', name: 'สระอุ', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20pot%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'อู', name: 'สระอู', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20owl%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'เอะ', name: 'สระเอะ', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20egg%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'เอ', name: 'สระเอ', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20eraser%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'แอะ', name: 'สระแอะ', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20ant%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'แอ', name: 'สระแอ', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20elephant%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'โอะ', name: 'สระโอะ', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20orange%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'โอ', name: 'สระโอ', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20bowl%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'เออะ', name: 'สระเออะ', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20bird%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'เออ', name: 'สระเออ', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20jar%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'เอียะ', name: 'สระเอียะ', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20beer%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'เอีย', name: 'สระเอีย', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20deer%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'เอือะ', name: 'สระเอือะ', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20bear%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'เอือ', name: 'สระเอือ', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20giraffe%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'อัวะ', name: 'สระอัวะ', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20flower%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'อัว', name: 'สระอัว', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20star%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'อำ', name: 'สระอำ', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20mango%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ไอ', name: 'สระไอ', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20ice%20cream%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ใอ', name: 'สระใอ', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20fire%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'เอา', name: 'สระเอา', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20cow%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'อวย', name: 'สระอวย', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20water%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'ออย', name: 'สระออย', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20toy%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'เอียว', name: 'สระเอียว', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20cat%20for%20kids%20thai%20style&image_size=square_hd' },
        { character: 'เอือว', name: 'สระเอือว', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20dog%20for%20kids%20thai%20style&image_size=square_hd' }
    ],
    
    finals: [
        { group: 'แม่กก', example: 'กก', desc: 'เสียงก', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20chicken%20for%20kids%20thai%20style&image_size=square_hd' },
        { group: 'แม่กด', example: 'กด', desc: 'เสียงด', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20child%20for%20kids%20thai%20style&image_size=square_hd' },
        { group: 'แม่กบ', example: 'กบ', desc: 'เสียงบ', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20leaf%20for%20kids%20thai%20style&image_size=square_hd' },
        { group: 'แม่กง', example: 'กง', desc: 'เสียงง', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20snake%20for%20kids%20thai%20style&image_size=square_hd' },
        { group: 'แม่กน', example: 'กน', desc: 'เสียงน', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20mouse%20for%20kids%20thai%20style&image_size=square_hd' },
        { group: 'แม่กม', example: 'กม', desc: 'เสียงม', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20horse%20for%20kids%20thai%20style&image_size=square_hd' },
        { group: 'แม่เกย', example: 'เกย', desc: 'เสียงย', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20giant%20for%20kids%20thai%20style&image_size=square_hd' },
        { group: 'แม่เกอว', example: 'เกอว', desc: 'เสียงว', audio: '', illustration: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cute%20cartoon%20ring%20for%20kids%20thai%20style&image_size=square_hd' }
    ]
};
